<!-- 
 * @package     Triangle Framework (WebKit)
 * @link        https://github.com/localzet/WebKit
 * @link        https://github.com/Triangle-org/Framework
 * 
 * @author      Ivan Zorin (localzet) <creator@localzet.com>
 * @copyright   Copyright (c) 2018-2022 Localzet Group
 * @license     https://www.localzet.com/license GNU GPLv3 License
-->
<?php
/*
 * Темы
 */

$hour = (int) date('H');

/** 
 * Светлая
 */

if ($hour >= 6 && $hour < 8) {
  $light_time = "sunrise";
} elseif ($hour >= 8 && $hour < 11) {
  $light_time = "late-morning";
} elseif ($hour >= 11 && $hour < 14) {
  $light_time = "midday";
} elseif ($hour >= 13 && $hour < 18) {
  $light_time = "afternoon";
} elseif ($hour >= 18 && $hour < 22) {
  $light_time = "evening";
} else {
  // $light_time = "night";
  $light_time = "evening";
}

/**
 * Тёмная
 */

if ($hour >= 6 && $hour < 12) {
  $dark_time = "Sunrise";
} elseif ($hour >= 12 && $hour < 16) {
  $dark_time = "Day";
} elseif ($hour >= 16 && $hour < 18) {
  $dark_time = "Evening";
} elseif ($hour >= 18 && $hour < 22) {
  $dark_time = "Twilight";
} else {
  $dark_time = "Night";
}
?>
<!DOCTYPE html>

<html lang="ru" prefix="og: http://ogp.me/ns#">

<head>
  <base href="" />
  <title><?= $name ?></title>
  <meta charset="utf-8" />

  <!-- About App -->
  <meta name="language" content="RU" />
  <meta name="robots" content="noindex,nofollow" />
  <meta name="title" content="<?= $name ?>" />
  <meta name="viewport" content="<?= $viewport ?>" />

  <!-- About Creator App -->
  <meta name="owner" content="<?= $owner ?>" />
  <meta name="designer" content="<?= $designer ?>" />
  <meta name="author" content="<?= $author ?>" />
  <meta name="copyright" content="<?= $copyright ?>" />
  <meta name="reply-to" content="<?= $reply_to ?>" />

  <!-- About System -->
  <meta name="project" content="<?= $name ?>" />
  <meta name="generator" content="Triangle Framework (WebKit)" />
  <meta name="FrameX" version="<?= config('app.version', '!notSET!') ?>" debug="<?= config('app.debug', '!notSET!') ?>" />
  <meta name="RootX" domain="<?= config('app.domain', '!notSET!') ?>" assets="<?= config('app.src', '!notSET!') ?>" />

  <!-- Cache&Content -->
  <meta http-equiv="Expires" content="60" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Cache-Control" content="no-cache" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <!-- Apple Meta Tags -->
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-touch-fullscreen" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <meta name="format-detection" content="telephone=no" />

  <!-- SEO -->
  <link rel="icon" type="image/svg+xml" href="<?= $logo ?>" />
  <link rel="shortcut icon" type="image/svg+xml" href="<?= $logo ?>" />

  <meta name="color-scheme" content="dark light">
  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#12121200">
  <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff00">

  <!-- Fonts -->
  <!-- <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Nunito:100,200,300,400,500,600,700,800,900" /> -->

  <!--Theme-->
  <script>
    var AppInfo = <?= json($AppInfo) ?>;
    var globalDebug = <?= config('app.debug') ? 'true' : 'false' ?>;
    var defaultThemeMode = "dark";
    var themeMode;
    if (document.documentElement) {
      if (document.documentElement.hasAttribute("data-theme-mode")) {
        themeMode = document.documentElement.getAttribute("data-theme-mode");
      } else {
        if (localStorage.getItem("data-theme") !== null) {
          themeMode = localStorage.getItem("data-theme");
        } else {
          themeMode = defaultThemeMode;
        }
      }
      if (themeMode === "system") {
        console.log(window.MediaDeviceInfo);
        themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
      }
      document.documentElement.setAttribute("data-theme", themeMode);
      AppInfo.theme = themeMode;
    }
    if (globalDebug) console.info("Запуск \"" + AppInfo.name + "\" \n", AppInfo);
  </script>
</head>

<body>
  <br />
  <center>
    <h1>
      <?= print_r($data, true) ?>
    </h1>
  </center>
  <hr />
  <center>
    Работает на <a href="https://github.com/Triangle-org">Triangle Web</a></center>
</body>

</html>